### PR TITLE
RPC method docs

### PR DESCRIPTION
**Pull request by J-Thompson12**
Closes: #https://github.com/ChainSafe/ethermint/issues/495

## Description

This is all the rpc methods i could find and get working. I have a list at the bottom i need to format that shows which ones are not implemented or just not important. I also have some where i couldnt get them to work because i dont know the parameter or how to get the parameter.
-->

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Comment by J-Thompson12** [comment]
Methods that are missing info

eth_getStorageAt need store key

eth_sendRawTransaction need to get signed transaction data for param

eth_call need toe get a not empty result

eth_getTransactionByHash find hash of transaction for param

eth_getFilterChanges not empty result

eth_getFilterLogs always get error 
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"filter 0x35b64c227ce30e84fc5c7bd347be380e doesn't have a LogsSubscription type: got 5"}}

eth_getLogs need not empty result

eth_getProof need address store key 

eth_subscribe and eth_unsubscribe don't know params

**Comment by noot** [comment]
@J-Thompson12 it looks like `eth_getProof` isn't in the ethereum API anymore: https://eth.wiki/json-rpc/API

for `eth_getStorageAt`, the storage key is the contract address according to the above

for `eth_call` are you deploying a contract w/ some storage and calling the contract to get that storage? if there is no return value for the tx then the call result will be empty

for `eth_subscribe`,`eth_unsubscribe`, `eth_getFilterChanges`, `eth_getFilterLogs`, could you try the instructions here and let me know what happens? https://github.com/ChainSafe/ethermint/pull/357

**Comment by fedekunze** [comment]
Thanks Justin! Could you also add a table  summary with the name of the method, a namespace column (name of the namespace of the endpoint) and an implemented column (with check) on the top of the doc?

**Review by fedekunze — COMMENTED** [review]
Thanks @J-Thompson12 for doing this audit!

I think we are missing a few namespaces from the [Geth Docs](https://geth.ethereum.org/docs/rpc/server) (eg: personal, miner, etc), many of them which don't apply to Etheremint (just stating that would suffice) and some methods from the [JSON-RPC Ethereum Wiki](https://eth.wiki/json-rpc/API#json-rpc-methods) (eg: `db_`, `ssh_` and maybe others).

If you want we can merge this PR as is and then open an issue to track the remaining pieces of work that are missing. As you prefer

**Comment by J-Thompson12** [comment]
Yeah i learned about those missing ones end of yesterday. It would be good to merge now and i can add the rest today. Colin wants to look at it.

**Comment by fedekunze** [comment]
@J-Thompson12 sounds good. Can you create an issue to track the progress? 🙏

**Review by fedekunze — APPROVED** [review]
ACK. Pending follow-up changes

**Pull request merged**
