### PR TITLE
fix panic when start a node with snapshot

### LINKED ISSUE #672: panic "wrong Block.Header.AppHash" happened when restart a node with snapshot
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

__Steps to reproduce:__
Reproduce every time

1. [First Step]
* Deploy 4 node with ethermintd

2. [Second Step]
* Publish some contract and call it on ethermint

3. [and so on...]
* Restart one of nodes

__Expected behavior:__ [What you expected to happen]
Node runs well

__Actual behavior:__ [What actually happened]
Panic happened, following code is error logs:
```shell
panic: Failed to process committed block (343:9150EFAEF4EBF5D9FF30BC07677883BBB69CC2FAE0AFB4FA38E27B6A2CE3C983): wrong Block.Header.AppHash.  Expected B54B85040B67913D1591D3AB62BE9F439852C67FD6C237BCACC3CA247B10C977, got AB17E63A9276B773384161A5A06A63897DC3985F30CF1EA7BF19309720CFF20C

goroutine 165 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc0001876c0)
        /Users/oker/work/go/pkg/mod/github.com/okex/tendermint@v0.33.9-okexchain1/blockchain/v0/reactor.go:349 +0x12ed
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /Users/oker/work/go/pkg/mod/github.com/okex/tendermint@v0.33.9-okexchain1/blockchain/v0/reactor.go:118 +0x84

```

__Additional info:__ [Include gist of relevant config, logs, etc.]

### PR DESCRIPTION
**Pull request by KamiD**
Closes: #672 

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Review by fedekunze — COMMENTED** [review]
A better alternative is to update the `evm.NewKeeper` constructor to return a pointer of the keeper and pass that to the app and the module manager.

**Comment by KamiD** [comment]
> A better alternative is to update the `evm.NewKeeper` constructor to return a pointer of the keeper and pass that to the app and the module manager.

Agree with you

**Comment by KamiD** [comment]
> A better alternative is to update the `evm.NewKeeper` constructor to return a pointer of the keeper and pass that to the app and the module manager.

@fedekunze I have finished the change by your point

**Review by fedekunze — APPROVED** [review]
LGTM. Can you add a changelog bugfix entry?

**Comment by KamiD** [comment]
> Seems that `test-importer` is failing

test-importer has been fixed but run test action failed because of github throw an internal error

**Comment by KamiD** [comment]
> Seems that `test-importer` is failing

Done

**Pull request merged**
